### PR TITLE
CSHARP-1849: Enable Plain Auth Tests

### PR DESCRIPTION
**Pull request by durran**
https://spruce.mongodb.com/version/5ffc4cfb3627e07c23e83ae6/tasks

Screenshot 2021-01-11 at 15 00 35

### CODE REVIEW

**Review by JamesKovacs — CHANGES_REQUESTED** [review]
When I tried to run the plain auth tests locally, all tests were skipped because they all include:

```
            RequireEnvironment.Check().EnvironmentVariable("EXPLICIT");
```

With the environment variable `EXPLICIT=1` set, 2 out of 3 fail on OSX. I haven't tried on Windows or Linux.

Looking at the Evergreen build results, there are no logs attached. So I'm not convinced that the tests are actually running successfully on Evergreen. I don't see that on Evergreen we set `EXPLICIT` either. So I am concerned that the 3 PLAIN/LDAP auth tests are actually just being skipped rather than run.

Please verify that the tests are actually being run on Windows/Linux/OSX and then I'll be happy to LGTM.

**Comment by JamesKovacs** [comment]
Looking at other tests like Data Lake and Atlas connectivity, we should choose a better environment variable name than `EXPLICIT`. For example, Data Lake tests use `ATLAS_DATA_LAKE_TESTS_ENABLED`. Maybe `LDAP_TESTS_ENABLED` or `PLAIN_AUTH_TESTS_ENABLED`?

**Comment by durran** [comment]
@JamesKovacs I updated to use `PLAIN_AUTH_TESTS_ENABLED` and fixed the failing test (it was asserting the wrong exception). Evergreen link in the description is now updated.

**Review by JamesKovacs — APPROVED** [review]
I was able to successfully run the tests on OSX with those changes. I debugged through the tests to ensure that they were actually run and not simply skipped due to missing preconditions (like the missing `EXPLICIT` env var previously).

LGTM

**Pull request merged**
